baseurl = "http://sshanshans.github.io/stat140/"
languageCode = "en-us"
defaultContentLanguage = "en-us"
title = "Stat 140 (Fall 2020)"
theme = "material"
paginate = 7
relativeURLs = false
uglyURLs = true
publishDir = "docs"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]


[permalinks]
  post = "/:year/:month/:slug/"

[taxonomies]
  tag = "tags"
  category = "categories"
  archive = "archives"

[author]
  name = "Dr. Shan Shan"
  bio = ""
  job = "Assistant Professor of Statistics"
  location = "Mount Holyoke College"
  gravatarEmail = "sshan@mtholyoke.edu"
  # Your profile picture
  #  picture = ""
  twitter = "MT_statistics"
 
# Menu Configuration
[[menu.main]]
  weight = 1
  identifier = "home"
  name = "Home"
  url = "../stat140"
[[menu.main]]
  weight = 3
  identifier = "schedule"
  name = "Schedule"
  url = "../stat140/schedule.html"
[[menu.main]]
  weight = 2
  identifier = "policies"
  name = "Syllabus"
  url = "../stat140/policies.html"
[[menu.main]]
  weight = 4
  identifier = "rstudio"
  name = "RStudio"
  url = "https://rstudio.cloud"
[[menu.main]]
  weight = 5
  identifier = "moodle"
  name = "Moodle"
  url = "https://moodle.mtholyoke.edu"
[[menu.main]]
  weight = 6
  identifier = "help"
  name = "Piazza"
  url = "https://piazza.com"


[params]
  dateFormat = "January 2, 2006"
  background = "https://www.mtholyoke.edu/sites/default/files/Mount-Holyoke-College-aerial-200408-CH.png"
  favicon = "img/sta199-sticker.png"
