baseurl = "http://sshanshans.github.io/stat140/"
languageCode = "en-us"
defaultContentLanguage = "en-us"
title = "STAT 140"
theme = "material"
#disqusShortname = ""
# googleAnalytics = ""
paginate = 7
relativeURLs = true
uglyURLs = true
publishDir = "docs"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]


[permalinks]
  post = "/:year/:month/:slug/"

[taxonomies]
  tag = "tags"
  category = "categories"
  archive = "archives"

[author]
  name = "Dr. Shan Shan"
  bio = ""
  job = "Assistant Professor of Statistics"
  location = "Mount Holyoke College"
  gravatarEmail = "sshan@mtholyoke.edu"
  # Your profile picture
#  picture = ""
  twitter = "MT_statistics"
 
# Menu Configuration
[[menu.main]]
  weight = 1
  identifier = "home"
  name = "Home"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-home\"></i>"
  url = "/"
[[menu.main]]
  weight = 2
  identifier = "schedule"
  name = "schedule"
  pre = "<i class=\"material-icons\">calendar_today</i>"
  url = "/schedule.html"
[[menu.main]]
  weight = 3
  identifier = "policies"
  name = "Policies"
  pre = "<i class=\"material-icons\">dashboard</i>"
  url = "/policies.html"
[[menu.main]]
  weight = 4
  identifier = "rstudio"
  name = "RStudio"
  pre = "<i class=\"material-icons\">cloud</i>"
  url = "https://rstudio.cloud"
[[menu.main]]
  weight = 5
  identifier = "moodle"
  name = "Moodle"
  pre = "<i class='fab fa-github fa-lg'></i>"
  url = "https://moodle.mtholyoke.edu"
[[menu.main]]
  weight = 6
  identifier = "help"
  name = "Help"
  pre = "<i class=\"material-icons\">help</i>"
  url = "https://piazza.com"


[[menu.footer]]
  weight = 1
  identifier = "MHC"
  name = "Mount Holyoke College"
  pre = "<i class=\"button-icon fa fa-2x fa-map-marker\"></i>"
  url = "http://www.mtholyoke.edu/"
[[menu.footer]]
  weight = 2
  name = "RStudio"
  pre = "<i class=\"icon-rlogo\" style=\"font-size:150%\"></i>"
  url = "https://rstudio.cloud/"
[[menu.footer]]
  weight = 3
  identifier = "GitHub"
  name = "GitHub"
  pre = "<i class=\"button-icon fa fa-2x fa-github\"></i>"
  url = "https://github.com/STA199-Sp19"
[[menu.footer]]


[params]
  dateFormat = "January 2, 2006"
  background = "http://www2.stat.duke.edu/courses/Spring19/sta199.001/img/bikeshare-plots.png"
  favicon = "img/sta199-sticker.png"
