---
title: "01 EA -Categorical variables"
author: "Type your name here"
output:
  pdf_document: default
  html_document:
    highlight: pygments
    theme: spacelab
---

```{r setup, include=FALSE}
# DO NOT ALTER CODE IN THIS CHUNK
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
```

* * *

# Load the data and R packages 
First make sure that you have installed the packages `tidyverse` and `mosaicData`. To check, go to the Packages tab on the lower right. 

```{r, include = FALSE, echo = FALSE, warning=FALSE}
library(tidyverse) 
library(mosaicData) 
```

```{r data}
data(Whickham)
```

#### Exercise 1: 
[Enter your response for Exercise 1 here.]

```{r ex1}
# enter your code for Exercise 1 here
```

#### Exercise 2:

[Enter your response for Exercise 2 here.]

```{r ex2}
# enter your code for Exercise 2 here
```

#### Exercise 3:

[Enter your response for Exercise 3 here.]

```{r ex3}
# enter your code for Exercise 3 here
```

#### Exercise 4:

#### Exercise 5:

#### Exercise 6:
