---
title: "Week 4 Day 1"
output: 
  html_document:
    css: lab.css
    highlight: pygments
    theme: cerulean
  pdf_document: default
---

### Magic of randomness: causality

#### Learning objectives 
* Recognize and know the elements of a designed randomized experiment.
* State and apply the Four Principles of Experimental Design.
    * Control sources of variation other than the factors being tested. Make the condi- tions as similar as possible for all treatment groups except for differences among the treatments.
    * Randomize the assignment of participants to treatments.
    * Replicate by applying each treatment to more than one participant.
    * Block the experiment by grouping together participants who are similar in important ways that you cannot control.
* Work with blinding and control groups.
* Be alert for possible confounding due to a variable that is not under control affecting the responses differentially.

#### Checklist
- <input type="checkbox" unchecked> Finish reading: [Chapter 7](https://nustat.github.io/intro-stat-ds/7-causality.html)
</input>

