---
title: "Week 4 Day 4"
output: 
  html_document:
    css: lab.css
    highlight: pygments
    theme: cerulean
  pdf_document: default
---

###  Normal distribution

#### Learning objectives 

* Understand normal distribution is completely determined by its mean and standard deviation
* Define the standardized (Z) score of a data point as the number of standard deviations it is away from the mean: $Z=(x−\mu)/\sigma$
* Use the Z score:
    * if the distribution is normal: to determine the percentile score of a data point (using technology or normal probability tables)
    * regardless of the shape of the distribution: to assess whether or not the particular observation is considered to be unusual (more than 2 standard deviations away from the mean)
* Depending on the shape of the distribution determine whether the median would have a negative, positive, or 0 $Z$ score keeping in mind that the mean always has a Z score of 0.
* Assess whether or not a distribution is nearly normal using the 68-95-99.7% rule or graphical methods such as a normal probability plot.

#### Checklist
- <input type="checkbox" unchecked> Finish reading: [Chapter 9.5](https://nustat.github.io/intro-stat-ds/9-sampling.html)
</input>