---
title: "Unit 2 Day 2"
output: 
  html_document:
    css: lab.css
    highlight: pygments
    theme: cerulean
  pdf_document: default
---

### Numerical variable: summary of histogram

#### Learning objectives 
* **Find a 5-number summary and, using it, make a boxplot. **
  * A 5-number summary consists of the median, the quartiles, and the extremes of the data.
  * A boxplot shows the quartiles as the upper and lower ends of a central box, the median as a line across the box, and “whiskers” that extend to the most extreme values that are not nominated as outliers.

* **Use the boxplot’s outlier nomination rule** to identify cases that may deserve special attention.
  * Boxplots display separately any case that is more than 1.5 IQRs beyond each quartile. These cases should be considered as possible outliers.

* **Understand the definition of the mean and standard deviation**
  * The mean is the sum of the values divided by the count. It is a suitable summary for unimodal, symmetric distributions.
  * The standard deviation is roughly the square root of the average squared difference between each data value and the mean. It is the summary of choice for the spread of unimodal, symmetric variables.

* **Understand when to use (median and IQR) and (mean and standard deviation)**
  * We’ll report the median and IQR when the distribution is skewed. 
  * If it’s symmetric, we’ll summarize the distribution with the mean and standard deviation (and possibly the median and IQR as well). 
  * Always pair the median with the IQR and the mean with the standard deviation.

#### Before class
* Finish the video: [Measure of center](https://www.coursera.org/learn/probability-intro/lecture/AM0o6/measures-of-center) and [Measure of spread](https://www.coursera.org/learn/probability-intro/lecture/t9Wbk/measures-of-spread)
* Finish reading: [U2D2 numerical variables](https://piazza.com/class_profile/get_resource/kcqqet0ou724kc/kehmc1c0l7slt)
* Complete `05 Quiz`: [VPN](http://138.110.84.108:3838/sshan/quiz/Unit2/), [nonVPN](http://159.89.233.150:3838/stat140/quiz/Unit2/)

#### In class
* Slides [html](https://sshanshans.github.io/stat140/slides/u2d2.pdf)
* Working on `06 Exercise`: [VPN](http://138.110.84.108:3838/sshan/tutorials/u2d2/), [nonVPN](http://159.89.233.150:3838/stat140/tutorials/u2d2/)

#### Items due
* `05 Quiz` [submit here](https://moodle.mtholyoke.edu/mod/assign/view.php?id=560974) due 09/01 6pm EST
* `06 Exercise` [submit here](https://moodle.mtholyoke.edu/mod/assign/view.php?id=560979) due 09/01 6pm EST