---
title: "Unit 2 Day 3"
output: 
  html_document:
    css: lab.css
    highlight: pygments
    theme: cerulean
  pdf_document: default
---

### Numerical variable: relationship, association and correlation

#### Learning objectives 
* **Make a scatterplot to display the relationship between two quantitative variables.**
  * Look at the direction, form, and strength of the relationship, and any outliers that stand away from the overall pattern.
* **Provided the form of the relationship is straight, summarize its strength with a correlation, r.**
  * The sign of the correlation gives the direction of the relationship.
  * -1 <= r <= 1 ; A correlation of 1 or -1 is a perfect linear relationship. A correlation of 0 indicates that there is no linear relationship.
  * Correlation has no units, so shifting or scaling the data, standardizing, or even swap- ping the variables has no effect on the numerical value.
* **A large correlation is not a sign of a causal relationship.**

#### Before class
* Finish watching: [Scatterplot (before 4:10)](https://www.coursera.org/learn/probability-intro/lecture/9kRJf/visualizing-numerical-data), [Correlation](https://www.coursera.org/learn/linear-regression-model/lecture/QP6Mw/correlation)
* Finish reading: [U2D3 numerical vars](https://piazza.com/class_profile/get_resource/kcqqet0ou724kc/kehmi5kwchrme) (You can safely ignore any formulas about the correlation score, and everything in the Kendall's Tau and Spearman’s Rho part.)
* Complete `06 Quiz`: [VPN](http://138.110.84.108:3838/sshan/quiz/Unit2/#section-quiz-2), [nonVPN](http://159.89.233.150:3838/stat140/quiz/Unit2/#section-quiz-2)

#### In class
* Slides post after class
* Working on ```07 Exercise```

#### Items due
* `06 Quiz` [submit here](https://moodle.mtholyoke.edu/mod/assign/view.php?id=560975) due 09/02 6pm EST
* `07 Exercise` [submit here](https://moodle.mtholyoke.edu/mod/assign/view.php?id=560980) due 09/02 6pm EST