---
title: "Unit 2 Day 5"
output: 
  html_document:
    css: lab.css
    highlight: pygments
    theme: cerulean
  pdf_document: default
---

### Putting it all together: exploratory data analysis

#### Learning objectives 
* **Revisit data visualization basics**
  * Create graphs with ```ggplot2``` in R
  * Add variables to a graph with ```aes```thetics
  * Create different types of graphs with ```geoms```
  * Understand the grammar rules of creating graphs with ```ggplot2```
* **Revisit data wrangling basics for numerical varibles**
  * Arrange
  * `group_by`
  * Summary statistics
* **Customize ggplot**
  * Add labels and titles
  * Customize color
  * Remove background grids

#### Before class
* Finish reading Chapter 1 in [Data Visualization: A practical introduction](https://socviz.co/lookatdata.html#lookatdata)
* Finish `07 Quiz` (Post on Piazza a bad graph you found online and comment on how you would improve the graph)

#### In class 
* Working on `08 Exercise`: [intro](http://sshanshans.github.io/stat140/labs/u2d4/intro)

#### Items due
* `07 Quiz` [submit here](https://piazza.com/class/kcqqet0ou724kc?cid=33) due on Piazza 09/04 6pm EST
* `08 Exercise` [submit here](https://moodle.mtholyoke.edu/mod/assign/view.php?id=560983) due 09/04 6pm EST
* `01 EA` [submit here](https://moodle.mtholyoke.edu/mod/assign/view.php?id=547286) due 09/04 6pm EST. [grading guideline](https://sshanshans.github.io/stat140/eas/EA1grading.pdf)

#### Evaluative assignment
* `02 EA: Exploratory Data Analysis` due 09/11 6pm EST
  * [intro](https://sshanshans.github.io/stat140/eas/02/intro)
  * [grading guideline](https://sshanshans.github.io/stat140/eas/02/EA2grading.pdf)
  * [moodle portal](https://moodle.mtholyoke.edu/mod/assign/view.php?id=560984&forceview=1)
  * peer evaluation form: link TBA