---
title: "Unit 4 Day 2"
output: 
  html_document:
    css: lab.css
    highlight: pygments
    theme: cerulean
  pdf_document: default
---

### Designed experiments and observational studies

#### Learning objectives 
* Recognize observational studies.
* Recognize and know the elements of a designed randomized experiment.
* State and apply the Four Principles of Experimental Design.
    * Control sources of variation other than the factors being tested. Make the condi- tions as similar as possible for all treatment groups except for differences among the treatments.
    * Randomize the assignment of participants to treatments.
    * Replicate by applying each treatment to more than one participant.
    * Block the experiment by grouping together participants who are similar in important ways that you cannot control.
* Work with blinding and control groups.
* Understand the differences between experiments and surveys.
    * Surveys try to estimate facts (parameter) about a population, so they require a representative random sample from that population.
    * Experiments try to estimate the differences in the effects of treatments. They randomize a group of experimental units to treatments, but there is no need for the experimental units to be a representative sample from the population.
* Be alert for possible confounding due to a variable that is not under control affecting the responses differentially.

#### Before class
* Finish reading [u4d2](https://piazza.com/class_profile/get_resource/kcqqet0ou724kc/kf08zdacq484jp)
* Complete `12 Quiz`: [VPN](http://138.110.84.108:3838/sshan/quiz/Unit4), [nonVPN](http://159.89.233.150:3838/stat140/quiz/Unit4)

#### In-class
* Slides posted after class
* Working on `12 Exercise` [intro](http://sshanshans.github.io/stat140/labs/u4d2/)

#### Items due
* `12 Quiz` due on [moodle portal](https://moodle.mtholyoke.edu/mod/assign/view.php?id=567538) 09/15 6pm EST
* `12 Exercise` due on [moodle portal](https://moodle.mtholyoke.edu/mod/assign/view.php?id=567542) 09/15 6pm EST