---
title: "Unit 5 Day 1"
output: 
  html_document:
    css: lab.css
    highlight: pygments
    theme: cerulean
  pdf_document: default
---

### An excursion to probability

#### Learning objectives 

* Define the probability of an outcome as the proportion of times the outcome would occur if we observed the random process that gives rise to it an infinite number of times.
* Explain why the long-run relative frequency of repeated independent events settles down to the true probability as the number of trials increases, i.e. why the law of large numbers holds.
* Define disjoint (mutually exclusive) events as events that cannot both happen at the same time: If A and B are disjoint, P(A and B) = 0
* Distinguish between disjoint and independent events. 
    * If A and B are independent, then having information on A does not tell us anything about B (and vice versa).
    * If A and B are disjoint, then knowing that A occurs tells us that B cannot occur (and vice versa).
    * Disjoint (mutually exclusive) events are always dependent since if one event occurs we know the other one cannot.
* Draw Venn diagrams representing events and their probabilities.
* Define a probability distribution as a list of the possible outcomes with corresponding probabilities that obeys the following rules:
  * **Rule 1**: A probability is a number between 0 and 1. For any event $A$, $$0 \leq P(A) \leq 1$$
  * **Rule2**: The set of all possible outcomes of a trial must have probability 1.
$$P(S) = 1$$
This is called the Probability Assignment Rule.
  * **Rule 3**: The probability of an event not occurring is 1 minus the probability that it does occur.
$$P(A^C) = 1 − P(A)$$
The set of outcomes that are not in the event A is called the complement of $A$, and is denoted $A^C$. This is called the Complement Rule. 
  * **Rule 4**: For two disjoint events A and B, the probability that one or the other occurs is the sum of the probabilities of the two events.
$$P(A \text{ or } B) = P(A) + P(B),$$ 
provided that A and B are disjoint. Disjoint (or mutually exclusive) events have no outcomes in common. This is called The Addition Rule.
  * **Rule 5**: For two independent events A and B, the probability that both A and B occur is the product of the probabilities of the two events.
$$P(A \text{ and } B) = P(A) \times P(B),$$ 
provided that A and B are independent. This is called the Multiplication Rule.

#### Before class
* Finish watching [Introduction](https://www.coursera.org/learn/probability-intro/lecture/07vL4/introduction), [Probability rules](https://www.coursera.org/learn/probability-intro/lecture/qaYwc/disjoint-events-general-addition-rule), [Independence](https://www.coursera.org/learn/probability-intro/lecture/D1m0l/independence)
* Complete `Quiz 15`

#### In class
* Work on `Exercise 16`

#### Items due
* ```Quiz 15``` due 09/21 6pm EST
* ```Exercise 16``` due 09/21 6pm EST
