---
title: "Unit 5 Day 3"
output: 
  html_document:
    css: lab.css
    highlight: pygments
    theme: cerulean
  pdf_document: default
---

###  Binomial distribution

#### Learning objectives 

* Define the standardized ($Z$) score of a data point as the number of standard deviations it is away from the mean: $Z=(x−\mu)/\sigma$
* Use the $Z$ score:
    * if the distribution is normal: to determine the percentile score of a data point (using technology or normal probability tables)
    * regardless of the shape of the distribution: to assess whether or not the particular observation is considered to be unusual (more than 2 standard deviations away from the mean)
* Depending on the shape of the distribution determine whether the median would have a negative, positive, or 0 $Z$ score keeping in mind that the mean always has a Z score of 0.
* Assess whether or not a distribution is nearly normal using the 68-95-99.7% rule or graphical methods such as a normal probability plot.

#### Before class
* Finish watching [Introduction to normal distribution](https://www.coursera.org/learn/probability-intro/lecture/M71Nv/normal-distribution), [Example](https://www.coursera.org/learn/probability-intro/lecture/mwnU6/working-with-the-normal-distribution)
* Complete `17 Quiz` [VPN](http://138.110.84.108:3838/sshan/quiz/Unit5/), [nonVPN](http://159.89.233.150:3838/stat140/quiz/Unit5/)


#### In class
* Working on `18 Exercise`

#### Items due
* `17 Quiz` due 09/23 6pm EST
* `18 Exercise` due 09/23 6pm EST