---
title: "NC bike crashes"
author: ""
date: "`r Sys.Date()`"
output: 
  html_document: 
    fig_height: 4
    fig_width: 9
---

```{r load-packages, include=FALSE}
library(tidyverse)
library(dsbox)
```

### Filter for bike crashes in Residential development areas where driver age group is 0 to 19.

```{r filter-age}
ncbikecrash %>%
  filter(development=="Residential", driver_age_group=="0-19")
```

### Identify the most commonly occurring estimated speed for drivers.

```{r speed}
ncbikecrash %>%
    count(driver_est_speed) %>%
    arrange(-n)
```

The most commonly occuring is 0-5 mph.

### Remove text like `A:`, `B:`, etc. from the `bike_injury` variable and save the result in a new variable called `bike_injury_rec`, and check your work.

```{r relabel}
 ncbikecrash <- ncbikecrash %>% mutate(bike_injury_rec = case_when(
  str_detect(bike_injury, "A:") ~ "Disabling Injury", 
  str_detect(bike_injury, "B:") ~ "Evident Injury",
  str_detect(bike_injury, "C:") ~ "Possible Injury", 
  str_detect(bike_injury, "K:") ~ "Killed",
  str_detect(bike_injury, "O:") ~ "No Injury",
  TRUE ~ bike_injury
))

ncbikecrash %>%
  count(bike_injury, bike_injury_rec)
```
