---
title: "Modeling Paris Paintings"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages, echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(broom)
library(knitr)
```

```{r load-data, message=FALSE}
pp <- read_csv("data/paris_paintings.csv", na = c("n/a", "", "NA"))
```

## Height & Width

```{r m_ht_wt}
m_ht_wt <- lm(Height_in ~ Width_in, data = pp)
tidy(m_ht_wt)
```


## Height & landscape features

```{r m_ht_lands}
m_ht_lands <- lm(Height_in ~ factor(landsALL), data = pp)
tidy(m_ht_lands)
```

### Height & school

```{r m_ht_sch}
m_ht_sch <- lm(Height_in ~ school_pntg, data = pp)
tidy(m_ht_sch)
```

## Back to m_ht_wt

### Obtaining R-squared 

```{r}
glance(m_ht_wt)
glance(m_ht_wt)$r.squared # extract R-squared
```


## Exploring linearity & transformations
```{r}
pp_wt_lt_100 <- pp %>% 
  filter(Width_in < 100)
```


```{r}
m_lprice_wt <- lm(log(price) ~ Width_in, data = pp_wt_lt_100)
m_lprice_wt %>%
  tidy() %>%
  select(term, estimate) %>%
  mutate(estimate = round(estimate, 3))
```

### Price vs. surface and living artist

```{r}
pp_Surf_lt_5000 <- pp %>%
  filter(Surface < 5000)
```

```{r}
m_main <- lm(log(price) ~ Surface + factor(artistliving), 
             data = pp_Surf_lt_5000)
m_main %>%
  tidy() %>%
  select(term, estimate) %>%
  mutate(estimate = round(estimate, 5))
```



